# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos511"
  config.vm.box_url = "http://warmspare.hurley.nuodb.com/Vagrant/centos511/opscode_centos-5.11_chef-provisionerless.box"
  config.vm.synced_folder "../../..", "/repo"
  
  config.vm.provider :virtualbox do |vb|
  # vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision "shell", inline: "/vagrant/setup.sh"
end
